version: '3' 
services:
    server_mongo:
      image: mongo:latest
      volumes:
        - ./database:/data/db
      ports:
        - 27017:27017

    server:
      build: vheclis/casaecafep1:latest
      ports:
        - 8080:8080
      links:
        - server_mongo
      depends_on:
        - server_mongo
      environment:
        MONGODB_HOST: 'server_mongo'
